POST http://localhost:9000/api/v1/orders

{
    "region":         "Sub-Saharan Africa",
    "country":        "South Africa",
    "item_type":      "Fruits",
    "sales_channel":  "Offline",
    "order_priority": "M",
    "order_date":     "7/27/2012",
    "order_id":       443368995,
    "ship_date":      "7/28/2012",
    "units_sold":     1593,
    "unit_price":     9.33,
    "unit_cost":      6.92,
    "total_revenue":  14862.69,
    "total_cost":     11023.56,
    "total_profit":   3839.13
}